// Mocks generated by Mockito 5.2.0 from annotations
// in sample_golden_test/test/views/pages/home_page_golden_toolkit_riverpod/home_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sample_golden_test/repositories/count_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountRepository extends _i1.Mock implements _i2.CountRepository {
  MockCountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> get() => (super.noSuchMethod(Invocation.method(#get, []),
      returnValue: Future<int>.value(0)) as _i3.Future<int>);
}
